### ISSUE TITLE
TypeAnnotation is empty for inferred types

### ISSUE THREAD

**Issue by timstudt** [SwiftDocOrg/SwiftSemantics#11]
when parsing symbols, variables with inferred types don't get a typeAnnotation.

```swift
class SomeClass {
    let scheduler = DispatchQueue.global(qos: .background)
}
```
See printout below of a symbol as `Variable` result: `typeAnnotation` is nil 
```
▿ let scheduler = DispatchQueue.global(qos: .background)
  - attributes : 0 elements
  ▿ modifiers : 1 element
    ▿ 0 : private
      - name : "private"
      - detail : nil
  - keyword : "let"
  - name : "scheduler"
  - typeAnnotation : nil
  ▿ initializedValue : Optional<String>
    - some : "DispatchQueue.global(qos: .userInitiated)"
  - accessors : 0 elements
```

Is this intentional to only show explicit types?

When setting an explicit type it works fine:
```swift
class SomeClass {
    let scheduler: DispatchQueue  = .global(qos: .background)
}
```

**Comment by mattt** [comment]
This is intentional behavior. SwiftSemantics processes the AST generated by SwiftSyntax, which in the example you provided doesn't include an explicit type annotation. You can't determine the implicit type of a declaration without the Swift compiler.  We know from the Dispatch interface and [documentation](https://developer.apple.com/documentation/dispatch/dispatchqueue/2300077-global) that `DispatchQueue.global` is a class function that returns an `DispatchQueue` object, but the same syntax could describe an enumeration case, for example, `enum DispatchQueue { case global }`.
