### ISSUE TITLE
Problem bumping to 0.3.2

### ISSUE THREAD

**Issue by cflorion** [SwiftDocOrg/SwiftSemantics#18]
Hi,

First, thanks for this library which saved me days learning SwiftSyntax 😁

Second, I am having a problem updating SwiftSemantics from version `0.2.0` to `0.3.2` in my project's `Package.swift` 

The error shown in XCode is 
``` 
Dependencies could not be resolved because root depends on 'SwiftSemantics' 0.3.2..<1.0.0.
'SwiftSemantics' >= 0.3.2 cannot be used because no versions of 'SwiftSemantics' match the requirement 0.3.3..<1.0.0 and package 'swiftsemantics' is required using a stable-version but 'swiftsemantics' depends on an unstable-version package 'swift-syntax'.

Has anyone encountered this problem ?
Thanks 

``` 

My `Package.swift`file is: 
``` 
// swift-tools-version:5.3
import PackageDescription

let package = Package(
    name: "ModelGenerator",
    platforms: [ .macOS(.v10_15) ],
    products: [
        .executable(name: "ModelGenerator", targets: ["ModelGenerator"])
    ],
    dependencies: [
        .package(
            url: "https://github.com/apple/swift-argument-parser",
            from: "0.4.3"
        ),
        .package(
            name: "SwiftSemantics",
            url: "https://github.com/SwiftDocOrg/SwiftSemantics",
            from: "0.3.2"
        ),
    ],
    targets: [
        .target(
            name: "ModelGenerator",
            dependencies: [
                "ModelGeneratorCore",
                .product(name: "ArgumentParser", package: "swift-argument-parser"),
            ]
        ),
        .target(
            name: "ModelGeneratorCore",
            dependencies: [
                "SwiftSemantics",
            ]
        )
    ]
)

```

**Comment by mattt** [comment]
@cflorion Thanks for the kind words! 

The issue you're running into stems from a limitation in how Swift Package Manager resolves transitive dependencies. Because `SwiftSemantics` depends on an exact version of `swift-syntax`, you can't depend on `SwiftSemantics` with a non-exact requirement. 

The installation instructions in the README should work (if they don't, please let me know!) https://github.com/SwiftDocOrg/SwiftSemantics#installation

**Comment by wgy6055** [comment]
I think the point is that:
...but 'swiftsemantics' depends on an unstable-version package 'swift-syntax' ?

Because in Package@swift-5.4.swift,
```swift
    dependencies: [
        .package(name: "SwiftSyntax",
                 url: "https://github.com/apple/swift-syntax.git",
                 .revision("release/5.4")),
    ],
```
I'm using Xcode 12.5 which integrated Swift 5.4. I can still reproduce this problem.

**Comment by mattt** [comment]
@wgy6055 That's right, you'd need to specify an exact version of SwiftSemantics, too. I had that wrong in the README, but just updated it. Can you still reproduce with the latest instructions?

```swift
// swift-tools-version:5.3

import PackageDescription

let package = Package(
  name: "YourProject",
  dependencies: [
    .package(
        name: "SwiftSemantics",
        url: "https://github.com/SwiftDocOrg/SwiftSemantics",
        .exact("0.3.2")
    ),
    .package(name: "SwiftSyntax",
         url: "https://github.com/apple/swift-syntax.git",
         .revision("release/5.4")),
  ]
)
```

**Comment by wgy6055** [comment]
@mattt I can still reproduce. I'm using Xcode built-in Swift Package Managing function instead of editing Package.swift. So I just set like this 👇

<img width="738" alt="截屏2021-07-21 上午1 12 22" src="https://user-images.githubusercontent.com/12740149/126366937-38d989f4-eccd-4d30-af44-cbbaa70a362c.png">

But I got this 👇

<img width="733" alt="截屏2021-07-21 上午1 09 11" src="https://user-images.githubusercontent.com/12740149/126367019-c25afb28-9164-4764-85cb-923b5fddce9c.png">

I think we should change `.revision("release/5.4"))` into `.exact("some.stable.version")` to fix this problem.
PS. I tried to integrate by branch: main. I got passed. But I don't think it was a good solution :(

**Comment by tjprescott** [comment]
I too had to target "main" to add the package dependency as my source code doesn't live at the root of the repo and thus Package.swift doesn't work. Everything builds fine, but any time I try to run the project, I get a runtime error:

```
dyld: Library not loaded: @rpath/lib_InternalSwiftSyntaxParser.dylib
  Referenced from: ...
  Reason: image not found
```

**Comment by wgy6055** [comment]
>  I too had to target "main" to add the package dependency as my source code doesn't live at the root of the repo and thus Package.swift doesn't work. Everything builds fine, but any time I try to run the project, I get a runtime error:
> 
> 
> 
> ```
> 
> dyld: Library not loaded: @rpath/lib_InternalSwiftSyntaxParser.dylib
> 
>   Referenced from: ...
> 
>   Reason: image not found
> 
> ```

@tjprescott 
I found something from README of SwiftSyntax. I believe this is what you need.
> SwiftSyntax depends on the lib_InternalSwiftSyntaxParser.dylib/.so library which provides a C interface to the underlying Swift C++ parser. When you do swift build SwiftSyntax links and uses the library included in the Swift toolchain. If you are building an application make sure to embed _InternalSwiftSyntaxParser as part of your application's libraries.
