### ISSUE TITLE
Example doesn't run from Xcode

### ISSUE THREAD

**Issue by chriseidhof** [SwiftDocOrg/SwiftSemantics#2]
If you create a new swift package, open it in Xcode, and add the dependencies and sample code, it fails to run successfully:

```
dyld: Library not loaded: @rpath/lib_InternalSwiftSyntaxParser.dylib
  Referenced from: /Users/chris/Library/Developer/Xcode/DerivedData/swiftmodulevis-dsdxeurkiqwybuaykcssnhgivnum/Build/Products/Debug/swiftmodulevis
  Reason: image not found
```

I forgot what causes this bug. Running/building from the terminal works fine. Maybe good to either add a notice or fix this? (I don't have time but wanted to let you know anyway).

This is Xcode 11.3 on Mojave.

**Comment by mattt** [comment]
Thanks for writing in about this, @chriseidhof. I was hitting the same issue when [trying to run unit tests](https://github.com/SwiftDocOrg/SwiftSemantics#known-issues). I think upgrading SwiftSyntax to a newer release should fix the issue, but I'd held off on that until I shipped this initial release. This is a great reminder to take another look.

**Comment by mattt** [comment]
@chriseidhof I tried fixing this by targeting a different release of SwiftSyntax, but wasn't able to get any of the other tags to work. Until a better solution is provided upstream, my suggestion would be to run `swift package generate-xcodeproj` to generate an Xcode project and then `xed <#Package#>.xcodeproj` to open the generated project directly.

**Comment by mattt** [comment]
@chriseidhof I'm happy to report that this is fixed in the latest Swift 5.2 development builds. I'll wait to close this until the most recent Xcode GM can build and run tests on SwiftSemantics `master` without a problem.

**Comment by mattt** [comment]
Update: It looks like this still isn't working in Xcode 11.4.

**Comment by liamnichols** [comment]
Its not a proper fix, but I did manage to have some luck in Xcode 12.2 by doing the following:

1. Edit the scheme, add the `DYLD_PRINT_RPATHS` environment var and set it's value to `1`
2. Look at the console output to see the directory where the dylib is trying to be loaded from 
3. Find the dylib in Xcode (i.e `find /Applications/Xcode-12.2.app -name lib_InternalSwiftSyntaxParser.dylib`)
4. Add a symbolic between where the actual dlyb is in Xcode and where the library is trying to be loaded from

Not ideal, but was enough to get things working at least so I could poke around rather than generating the xcodeproj

**Comment by mattt** [comment]
I'm very happy to report that this is working in Xcode 12.5 with the latest [OSS Toolchain](https://swift.org/download/). I updated the README with fb4aa1318e4809e77d3b39ba38a9ddaf462d8835.
