### ISSUE TITLE
`typeAnnotation` is nil for type inference 

### ISSUE THREAD

**Issue by yingmu52** [SwiftDocOrg/SwiftSemantics#20]
# Problem 
I found `typeAnnotation` is nil when a variable is declared with type inference

# Example 
```
func makeSession() -> Session

class MediaPlayer {
     let session = makeSession()
}
```

result: 
```
name: session, typeAnnotation: nil
```

expected result
```
name: session, typeAnnotation: Session
```

I think this might be an issue in [SwiftSyntax](https://github.com/apple/swift-syntax), but I am not sure if this is by design.

**Comment by mattt** [comment]
Hi @yingmu52. This is expected behavior. 

SwiftSyntax (and therefore SwiftSemantics) provides an interface to an abstract syntax tree from Swift code. All it knows about the code is the black letter of what's written. If no explicit type is provided in the declaration, like it is here, then that's what gets reported. Type inference requires the Swift compiler.
